show info, sharedfeature, dataarea
SabreTools/SabreTools pull request #51
Opened 2021-11-28 15:47 UTC by Lothrien

show info and sharedfeature element
show additional dataareas in rom element

2021-11-28 16:10 UTC, Lothrien commented
this patch need #52, combine pulls is currently not a feature of github?

2022-02-22 21:11 UTC, mnadareski requested changes

2022-02-22 21:11 UTC, mnadareski commented on SabreTools.DatFiles/Formats/SoftwareList.cs
> +                        if (!String.IsNullOrEmpty(string.Join(", ", roms)))
I'd prefer consistency here in using `String` and `string` with a preference being on `string`.

2022-02-22 21:11 UTC, mnadareski commented on SabreTools.DatFiles/Formats/SoftwareList.cs
> +                ItemType.DataArea,
This may or may not be doing what you think it's doing. Did you look at how the `Rom` items are being written out?

2022-02-22 21:11 UTC, mnadareski commented on SabreTools.DatFiles/Formats/SoftwareList.cs
> +                        if (!String.IsNullOrEmpty(string.Join(", ", roms)))
I don't fully understand what this is supposed to be doing. Why are you joining a list of DatItems as if they're strings?

2024-10-22 15:39 UTC, closed without merging